# Generated by Django 5.1.5 on 2025-02-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Debtor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Ism va familiyasi')),
                ('social_link', models.TextField(blank=True, null=True, verbose_name='Ijtimoiy tarmoqdagi manzili')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon nomeri')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Manzili')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
