# Generated by Django 5.1.5 on 2025-02-04 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_product_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('sabzavot', 'Sabzavotlar'), ('meva', 'Meva'), ('gosht', "Go'sht mahsulotlari")], max_length=50, verbose_name='Kategoriya')),
                ('required_quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kerakli Miqdor')),
                ('measurement_unit', models.CharField(choices=[('kg', 'kg'), ('dona', 'dona'), ('litr', 'litr')], max_length=10, verbose_name="O'lchov Birligi")),
                ('status', models.CharField(choices=[('kutilyapti', 'Kutilyapti'), ('qabul_qilingan', 'Qabul qilindi'), ('bekor_qilingan', 'Bekor qilindi')], max_length=20, verbose_name='Holati')),
                ('note', models.TextField(blank=True, verbose_name="Qo'shimcha Izoh")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.product', verbose_name='Mahsulot Nomi')),
            ],
        ),
    ]
