# Generated by Django 5.1.5 on 2025-02-05 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_productrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Sabzavot', 'Sabzavot'), ('Meva', 'Meva'), ('Sut Mahsulotlari', 'Sut Mahsulotlari')], max_length=50, verbose_name='Kategoriya')),
                ('quantity', models.PositiveIntegerField(verbose_name="Boshlang'ich Miqdor")),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('dona', 'Dona'), ('litr', 'Litr')], max_length=10, verbose_name='Oʻlchov Birligi')),
                ('arrival_date', models.DateField(verbose_name='Kelgan Sana')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Olingan Narxi (so'mda)")),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Narxi (so'mda)")),
                ('expiry_date', models.DateField(verbose_name='Saqlash Muddat')),
                ('additional_info', models.TextField(blank=True, null=True, verbose_name="Qo'shimcha Ma'lumot")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.product', verbose_name='Mahsulot Nomi')),
            ],
        ),
    ]
